### ISSUE TITLE
Please open source other remote resources

### ISSUE THREAD

**Issue by maricn** [jamieecarr/nod#7]
Hi! First of all, thanks for the extension, it seems very useful. We'd like to start using it widely in my company, but are concerned about security and privacy of it. I've checked the privacy policy, but it would really give us ease of mind if you could be more open about what's going on the server side.

Looking through the code, I can see you're using a web socket service at wss://j24amtdvi4.execute-api.us-east-1.amazonaws.com/prod. Can you please publish the code running there? And also if you plan to use other remote resources and for what purpose.

Thank you!

**Comment by jamieecarr** [comment]
Hi @maricn, the WebSocket simply calls the lambda function in https://github.com/jamieecarr/nod/blob/master/backend/socket/socket.js

As you'll be able to see, no personal info for any individuals is stored, I am storing a list of teams using the tool, just for my own interest and to help with debugging.

**Comment by maricn** [comment]
Ah, didn't notice that piece of code and stuff in https://github.com/jamieecarr/nod/blob/master/deploy/prod/serverless.yml. Thank you for replying swiftly anyways and for your work on the extension!

Also, to make it more complete, it would be nice to have verifiable CI/CD build result showing that the code actually gets deployed to that particular amazon serverless domain.
